FROM python
MAINTAINER ronald
ADD ./ /data
RUN apt-get update -y && apt-get install python-dev python3-dev libsasl2-dev python-dev libldap2-dev libssl-dev -y
RUN pip install -U Flask flask_httpauth==4.1.0 flask_simpleldap python-dotenv==0.14.0
EXPOSE  5000
WORKDIR /data
ENTRYPOINT ["python", "student_age.py"]
